import { FaCloud, FaEnvelope, FaFlask, FaGithub, FaLinkedin, FaMoon, FaRedo, FaSun, FaWater } from 'react-icons/fa';
import { FaHouse } from 'react-icons/fa6';
import {
  SiAmazon,
  SiBitbucket,
  SiCss3,
  SiDocker,
  SiGatsby,
  SiGithubactions,
  SiGraphql,
  SiHtml5,
  SiInertia,
  SiJavascript,
  SiLaravel,
  SiLinux,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiPhp,
  SiPython,
  SiReact,
  SiSentry,
  SiTailwindcss,
  SiTypescript,
} from 'react-icons/si';

export const Icons = {
  // Navbar & theme
  github: FaGithub,
  linkedin: FaLinkedin,
  email: FaEnvelope,
  home: FaHouse,
  sun: FaSun,
  moon: FaMoon,
  php: SiPhp,
  laravel: SiLaravel,
  javascript: SiJavascript,
  tailwind: SiTailwindcss,
  mysql: SiMysql,
  react: SiReact,
  inertia: SiInertia,
  typescript: SiTypescript,
  nodejs: SiNodedotjs,
  python: SiPython,
  graphql: SiGraphql,
  nextjs: SiNextdotjs,
  gatsby: SiGatsby,
  html5: SiHtml5,
  css3: SiCss3,
  aws: SiAmazon,
  docker: SiDocker,
  githubactions: SiGithubactions,
  bitbucketpipelines: SiBitbucket,
  bitbucket: SiBitbucket,
  laravelforge: SiLaravel,
  laravelvalet: SiLaravel,
  linux: SiLinux,
  sentry: SiSentry,
  restapis: FaCloud,
  cicd: FaRedo,
  agile: FaRedo,
  waterfall: FaWater,
  oop: FaCloud,
  tdd: FaFlask,
  sql: FaCloud,
} as const;
