import {
  FaCloud,
  FaCode,
  FaEnvelope,
  FaFlask,
  FaGithub,
  FaGlobe,
  FaLinkedin,
  FaMoon,
  FaRedo,
  FaSun,
  FaWater,
} from 'react-icons/fa';
import { FaHouse } from 'react-icons/fa6';
import {
  SiAmazon,
  SiAnthropic,
  SiBitbucket,
  SiClaude,
  SiCss3,
  SiDocker,
  SiFastapi,
  SiGatsby,
  SiGithubactions,
  SiGithubcopilot,
  SiGraphql,
  SiHtml5,
  SiInertia,
  SiJavascript,
  SiLaravel,
  SiLinux,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiOpenai,
  SiPhp,
  SiPostgresql,
  SiPython,
  SiReact,
  SiRedis,
  SiSentry,
  SiShadcnui,
  SiSupabase,
  SiTailwindcss,
  SiTypescript,
} from 'react-icons/si';

export const Icons = {
  // Navbar & theme
  github: FaGithub,
  linkedin: FaLinkedin,
  email: FaEnvelope,
  home: FaHouse,
  sun: FaSun,
  moon: FaMoon,
  php: SiPhp,
  laravel: SiLaravel,
  javascript: SiJavascript,
  tailwind: SiTailwindcss,
  mysql: SiMysql,
  react: SiReact,
  inertia: SiInertia,
  typescript: SiTypescript,
  nodejs: SiNodedotjs,
  python: SiPython,
  graphql: SiGraphql,
  nextjs: SiNextdotjs,
  gatsby: SiGatsby,
  html5: SiHtml5,
  css3: SiCss3,
  aws: SiAmazon,
  docker: SiDocker,
  githubactions: SiGithubactions,
  bitbucketpipelines: SiBitbucket,
  bitbucket: SiBitbucket,
  laravelforge: SiLaravel,
  laravelvalet: SiLaravel,
  linux: SiLinux,
  sentry: SiSentry,
  restapis: FaCloud,
  cicd: FaRedo,
  agile: FaRedo,
  waterfall: FaWater,
  oop: FaCloud,
  tdd: FaFlask,
  sql: FaCloud,
  external: FaGlobe,
  fastapi: SiFastapi,
  postgresql: SiPostgresql,
  redis: SiRedis,
  shadcn: SiShadcnui,
  openai: SiOpenai,
  rq: FaRedo,
  claude: SiClaude,
  anthropic: SiAnthropic,
  copilot: SiGithubcopilot,
  supabase: SiSupabase,
  opencode: FaCode,
} as const;
